# Используем официальный образ .NET SDK для сборки проекта
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем .csproj файл и восстанавливаем зависимости
COPY *.csproj ./
RUN dotnet restore

# Копируем все файлы проекта в контейнер
COPY . ./

# Собираем проект
RUN dotnet publish -c Release -o out

# Используем официальный образ .NET для выполнения приложения
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем скомпилированное приложение из стадии build
COPY --from=build /app/out .

# Открываем порт 80 для приложения
EXPOSE 80

# Запускаем приложение
ENTRYPOINT ["dotnet", "PortfolioAPI.dll"]
